Majjaka_eProcure/urls.py
# URL file for handling search and users app path

# Importing Django standard library
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Defining the mapping between URLs and views
urlpatterns = [
    path('admin/', admin.site.urls),                                    # Admin page
    path('', include('eProc_Login.urls')),
    path('', include('django.contrib.auth.urls')),                      # Forgot password urls
    path('upload/', include('eProc_Upload.urls')),                      # Upload SC PO data
    path('shop/', include('eProc_Shopping_Cart.urls'), name='shop'),
    path('notes_attachments/', include('eProc_Notes_Attachments.urls')),
    path('search/', include('eProc_Doc_Search.urls')),
    path('doc_details/', include('eProc_Doc_Details.urls')),
    path('usersettings/', include('eProc_User_Settings.urls'), name='usersettings'),
    path('register/', include('eProc_Registration.urls')),
    path('Reports/', include('eProc_Reports.urls')),
    path('Rfq/', include('eProc_Rfq.urls')),
    path('admin_tool/', include('eProc_Admin_Tool.urls')),
    path('org_model/', include('eProc_Org_Model.urls')),
    path('eProc_User_Admin/', include('eProc_User_Admin.urls')),
    path('system_setting/', include('eProc_System_Settings.urls')),
    path('attributes/', include('eProc_Attributes.urls')),
    path('configuration/', include('eProc_Configuration.urls')),
    path('purchaser_cockpit/', include('eProc_Purchaser_Cockpit.urls'), name='purchaser_cockpit'),
    path('shop/', include('eProc_Catalog.urls')),
    path('workflow/', include('eProc_Workflow.urls'), name='workflow'),
    path('connector/', include('eProc_SAP_Connector.urls')),
    path('generate_pdf/', include('eProc_Generate_PDF.urls')),
    path('configure-freetext/', include('eProc_Form_Builder.urls')),
    path('notification/', include('eProc_Notification.urls')),
    path('chat/', include('eProc_Chat.urls')),
    path('sobo/', include('eProc_SOBO.urls')),
    path('account_assignment/', include('eProc_Account_Assignment.urls')),
    path('home/', include('eProc_Shop_Home.urls')),
    path('add_item/', include('eProc_Add_Item.urls')),
    path('support/', include('eProc_Org_Support.urls')),
    path('search/', include('eProc_Doc_Search_and_Display.urls')),
    path('users/', include('eProc_Users.urls')),
    path('suppliers/', include('eProc_Suppliers.urls')),
    path('manage-content/', include('eProc_Manage_Content.urls')),
    path('emails/', include('eProc_Emails.urls')),
    path('configuration/basic_settings/', include('eProc_Basic_Settings.urls')),
    path('Majjaka-Shop/', include('eProc_Basic.urls')),
    path('configuration/master_settings/', include('eProc_Master_Settings.urls')),
    path('configuration/application_settings/', include('eProc_Application_Settings.urls')),
    path('message-settings/', include('eProc_Messages.urls')),
    path('purchase_order/', include('eProc_Purchase_Order.urls')),
    path('configuration_check/', include('eProc_Configuration_Check.urls')),
    path('generate_otp/', include('eProc_Generate_OTP.urls')),
    path('setup_new_client/', include('eProc_New_Client_Setup.urls')),
    path('timesheet/', include('eProc_Time_Sheet.urls')),
    path('projects/', include('eProc_Projects.urls')),
    path('som/', include('eProc_Supplier_Order_Management.urls')),
    path('marketing/', include('eProc_Marketing.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eProc_Emails/urls.py
from django.urls import path

from .Utilities.email_notif_generic import email_notify
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'eProc_Emails'

urlpatterns = [
    path('eProc_Email_Notification/', email_notification_form, name='email_notif'),
    path('eProc_Email_Notification_Edit/', edit_email_notif_form, name='edit_email_notif_form'),
    path('eProc_Email_Notification_Update/', update_email_notif_form, name='update_email_notif_form'),
    path('resend_user_mail', resend_user_mail, name='resend_user_mail'),
]
# eProc_Email_Notification:update_email_notif_form
# eProc_Emails:update_email_notif_form

eProc_Rfq/urls.py
# URL file for handling '/search' path (search app)
from django.urls import path
from . import views

app_name = 'eProc_Rfq'


urlpatterns = [

   ]

eProc_Emails/views.py
from django.shortcuts import render

# Create your views here.

eProc_Emails/views/email_notification.py
"""Copyright (c) 2020 Hiranya Garbha, Inc. Name: email_notification.py Usage: On click of E-mails tab in Application
Settings email_notification_form - This function handles the display, modifying and saving the email notification
format and renders email_settings.html Author: Shilpa """
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction
from django.http import JsonResponse
from django.shortcuts import render

from Majjaka_eProcure import settings
from eProc_Add_Item.views import JsonParser_obj
from eProc_Basic.Utilities.constants.constants import CONST_USER_REG, CONST_ACTIVE, CONST_COFIG_UI_MESSAGE_LIST
from eProc_Basic.Utilities.functions.django_q_query import django_q_query
from eProc_Basic.Utilities.functions.django_query_set import DjangoQueries
from eProc_Basic.Utilities.functions.get_db_query import getClients
from eProc_Basic.Utilities.functions.guid_generator import guid_generator
from eProc_Basic.Utilities.functions.messages_config import get_msg_desc, get_message_desc
from eProc_Basic.Utilities.global_defination import global_variables
from eProc_Basic.Utilities.messages.messages import *
from eProc_Configuration.Utilities.application_settings_generic import get_configuration_data, get_ui_messages
from eProc_Configuration.models import NotifSettings, NotifKeywordsDesc, NotifSettingsDesc, EmailObjectTypes, \
    EmailKeywords, EmailContents, Languages
from eProc_Emails.Utilities.email_notif_generic import email_notify, appr_notify, send_po_attachment_email
from eProc_Emails.models import EmailUserMonitoring, EmailDocumentMonitoring, EmailSupplierMonitoring
from eProc_Registration.models import UserData
from eProc_Shopping_Cart.Utilities.shopping_cart_generic import get_SC_details_email
from eProc_Shopping_Cart.context_processors import update_user_info
from eProc_Shopping_Cart.models import ScHeader, ScPotentialApproval, ScApproval

django_query_instance = DjangoQueries()


@login_required
def email_notification_form(req):
    """
    handles email notification data for displaying, edit and saving
    :param req: request data from UI
    :return: renders emailnotif.html
    """
    update_user_info(req)
    client = global_variables.GLOBAL_CLIENT
    variant_list = []
    keyword_list = []

    # django_query_instance.django_filter_only_query(EmailObjectTypes, {'client': client, 'del_ind': False})
    object_type_data = django_query_instance.django_filter_only_query(EmailObjectTypes,
                                                                      {'client': client,
                                                                       'del_ind': False}).values('object_type')

    for variant_names in object_type_data:
        variant_list.append(variant_names['object_type'])
    try:
        keyword_data = django_query_instance.django_filter_only_query(EmailKeywords, {
            'client': client,
            'del_ind': False
        }).values('keyword')
        for dt in keyword_data:
            keyword_list.append(dt['keyword'])

        email_data = get_configuration_data(EmailContents, {'del_ind': False},
                                            ['email_contents_guid', 'object_type', 'subject', 'header', 'body',
                                             'footer', 'language_id'])
        language_list = list(django_query_instance.django_filter_only_query(Languages, {'del_ind': False}).values('language_id', 'description'))
        for data in email_data:
            for lang in language_list:
                if data['language_id'] == lang['language_id']:
                    data['lang_description'] = lang['description']

    except ObjectDoesNotExist:
        msg = messages.error(req, 'please maintain data')
        return render(req, 'emailnotif.html', msg)

    messages_list = get_ui_messages(CONST_COFIG_UI_MESSAGE_LIST)

    context = {
        'variant_list': variant_list,
        'keyword_list': keyword_list,
        'email_data': email_data,
        'messages_list': messages_list,
        'language_list': language_list,
        'inc_nav': True,
    }

    return render(req, 'Application_Settings/email_settings.html', context)


@transaction.atomic
def edit_email_notif_form(req):
    """
    Function to retrieve selected email notification type data.
    :param req:
    :return:
    """
    client = getClients(req)

    if req.is_ajax():
        keyword_list = []
        selected_variant = req.POST.get('variant_data')

        form_data1 = django_query_instance.django_get_query(EmailContents,
                                                            {'object_type': selected_variant, 'client': client,
                                                             'del_ind': False})

        keyword_data1 = django_query_instance.django_filter_only_query(EmailKeywords,
                                                                       {'object_type': selected_variant,
                                                                        'client': client, 'del_ind': False}).values(
            'keyword')

        for keywords in keyword_data1:
            keyword_list.append(keywords['keyword'])

        ajax_context = {
            'keyword_list': keyword_list,
            'email_contents_guid': form_data1.email_contents_guid,
            'subject': form_data1.subject,
            'body': form_data1.body,
            'header': form_data1.header,
            'footer': form_data1.footer
        }

        return JsonResponse(ajax_context)


@transaction.atomic
def update_email_notif_form(request):
    """
    This function is to update the edited email content data.
    :param request:
    :return:
    """
    if request.method == 'POST':
        update_email_guid = request.POST.get('email_guid')
        update_email_subject = request.POST.get('email_subject')
        update_email_header = request.POST.get('email_header')
        update_email_body = request.POST.get('email_body')
        update_email_footer = request.POST.get('email_footer')

        if update_email_guid is None:
            update_email_guid = guid_generator()
        update_email_notif_data = django_query_instance.django_filter_only_query(EmailContents,
                                                                                 {
                                                                                     'email_contents_guid': update_email_guid,
                                                                                     'del_ind': False})

        update_email_notif_data.update(subject=update_email_subject, header=update_email_header, body=update_email_body,
                                       footer=update_email_footer)
        error_msg = get_message_desc(MSG037)[1]
        # msgid = 'MSG037'
        # error_msg = get_msg_desc(msgid)
        # msg = error_msg['message_desc'][0]
        # error_msg = msg
        return JsonResponse({'message': error_msg})
        # return JsonResponse({'message': MSG037})


@transaction.atomic
def resend_user_mail(request):
    """
    This function is to update the edited email content data.
    :param request:
    :return:
    """
    global message, email_list, status
    variant_name = ''
    client = getClients(request)
    mgr_details = {}
    approver = []
    appr_flag = 0
    status = 0
    basic_data = JsonParser_obj.get_json_from_req(request)
    sc_email_data = []

    # for user in user_details:
    #     first_name = user['first_name']
    #     last_name = user['last_name']

    if request.is_ajax():
        for val in basic_data:
            username = val['username']
            email = val['email']
            email_user_monitoring_guid = val['email_user_monitoring_guid']
            variant_name = val['email_type']
            if variant_name == 'SC Approval' or variant_name == 'SC_APPROVAL':
                variant_name = 'SC_APPROVAL'
            elif variant_name == 'Supplier Order':
                variant_name = 'PO_SUPPLIER'
            user_details = django_query_instance.django_get_query(UserData, {'email': val['email'],
                                                                             'del_ind': False,
                                                                             'client': client})
            if variant_name == 'SC_APPROVAL':
                result = {}
                sc_email_details = django_query_instance.django_get_query(EmailDocumentMonitoring,
                                                                          {
                                                                              'email_document_monitoring_guid': email_user_monitoring_guid,
                                                                              'client': client,
                                                                              'object_type': variant_name,
                                                                              'del_ind': False})
                appr_flag = check_sc_approval_email(sc_email_details.doc_number)
                if appr_flag != 1:
                    sc_header_instance = django_query_instance.django_get_query(ScHeader,
                                                                                {'client': client,
                                                                                 'doc_number': sc_email_details.doc_number,
                                                                                 'del_ind': False,
                                                                                 })
                    app_step_number = django_query_instance.django_filter_value_list_query(ScPotentialApproval,
                                                                                           {

eProc_Emails/templates/emailnotif.html
{% extends 'root/base.html' %}
{% load static %}
{% block maincontent %}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>
    .ui-autocomplete { z-index:2147483647; }
</style>
<div id="Admintool" style="margin-top:20px;">
    <div class="container-fluid ml-5" style="width: 97%;">
       <div class="jumbotron bg-white">
        <div class="hg_limorder" style="width:100%;" >
            <div class="hg_limordertxt hg_pt20">
                <div class="hg_head1">Set up your E-mail Notifications</div>
                <hr class="hg_heading_hrborder">
            </div>

            <div style="width:70%; overflow:auto;">
                <div id="Notif_email" >
                    <form method="post">
                        {% csrf_token %}

                        <div>
                            {% if messages %}
                            {% for message in messages %}
                            <div class="{{ message.tags }}">{{ message }}</div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <span id="success_message" class="hg_success"></span>
                        <p id="demo"></p>

                        <div>
                            Choose a Email type:<br>
                            <select id="select_variant_type" class="form-control hg_mb10" onchange="select_variant();">
                                {% for vrnt_data in variant_list %}
                                <option>{{ vrnt_data }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <!-- Creating drop down for keywords w.r.t variant name  -->
<!--                        Available Keywords:<br>-->
<!--                        <select id="available_keywords" class="form-control hg_mb10">-->
<!--                            {% for keywrd_data in keyword_data %}-->
<!--                            <option>{{ keywrd_data.keyword }}</option>-->
<!--                            {% endfor %}-->
<!--                        </select>-->

                    </form>
                    <!-- Start of email notification form -->
                    <form id="email_notif_form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset disabled id="form_read_only">
                            <input id="email_guid" value="{{data_onload.0.email_contents_guid}}" hidden>
                            <label>Enter the E-mail subject:</label><br>
                            <input type="search" id="email_subject" class="form-control mb-2" value="{{data_onload.0.subject}}" onkeypress="typeahead(this.id)">
                            <label>Enter the E-mail content details:</label>
                            <textarea id="email_header" class="form-control" style="height:100px;" onkeypress="typeahead(this.id)" placeholder="Enter Header here">{{data_onload.0.header}}</textarea>
                            <textarea id="email_body" class="form-control" style="height:200px;" onkeypress="typeahead(this.id)" placeholder="Enter Body here">{{data_onload.0.body}}</textarea>
                            <textarea id="email_footer" class="form-control" style="height:100px;" onkeypress="typeahead(this.id)" placeholder="Enter Footer here">{{data_onload.0.footer}}</textarea>
                        </fieldset>
                        <div style="text-align:right; width:100%; overflow:auto; margin-top:10px;">
                            <button type="submit" id="save_en_button" class="btn btn-primary" style="display:none; float:right;" value="SAVE"><i class="fas fa-save"></i> &nbsp;save</button>
                        </div>
                    </form>
                    <div style="text-align:right; overflow:auto; margin-top:10px;">
                        <button type="button" id="edit_en_button" onclick="edit_en_button()" class="btn btn-primary" value="EDIT" style="float:right; "><i class="fas fa-pencil-alt"></i> &nbsp;edit</button>
                        <button type="button" id="cancel_en_button" onclick="cancel_en_button()" class="btn btn-primary" value="cancel" style="display:none; float:right; margin-right:20px;"><i class="fas fa-times"></i> &nbsp;cancel</button>&nbsp;
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>

</div><div id="box">&nbsp;</div>


<!--    <div id="loading_popup" class="hg_modal" >-->
<!--        <div class="hg_modal_content" style=" width:100px; height:150px;" >-->
<!--            <div class="hg_container" style=" width:100px; height:150px;">-->
<!--                <div id="output" >-->
<!--                    <h3>Please wait...</h3>-->
<!--                    <img  src="{% static 'img/loading.gif' %}" height="50px" width="50px"  alt="loading"/>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

        {% include 'root/loader.html' %}


<script>

nav_bar_admin();
var availableKeywords = [
        {% for data in keyword_list %}
            "{{data}}",
        {% endfor %}
    ];

    // function to retrieve email notification data using ajax request
    function select_variant() {
        var variant = document.getElementById("select_variant_type");
        variant_data = variant.options[variant.selectedIndex].value;
        document.getElementById('email_subject').value = "";
        document.getElementById('email_body').value = "";
        document.getElementById('email_header').value = "";
        document.getElementById('email_footer').value = "";
         $.ajax({
            type: 'POST',
            url: "{% url 'eProc_Emails:edit_email_notif_form' %}",
            data: {
                'variant_data': variant_data,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (response) {
                keywords = response.keyword_list
                $('#available_keywords').empty()
                for(i=0; i<keywords.length; i++){
                    available_keywords = '<option>' + keywords[i] + '</option>'
                    $('#available_keywords').append(available_keywords)
                }
                document.getElementById('email_guid').value = response.email_contents_guid;
                document.getElementById('email_subject').value = response.subject;
                document.getElementById('email_body').value = response.body;
                document.getElementById('email_header').value = response.header;
                document.getElementById('email_footer').value = response.footer;
            }
         })
    }

    // Edit button functionality
    function edit_en_button() {
        document.getElementById('form_read_only').disabled = false;
        document.getElementById('edit_en_button').style.display = 'none'
        document.getElementById('cancel_en_button').style.display = 'block'
        document.getElementById('save_en_button').style.display = 'block'
    }

    // Cancel button functionality
    function cancel_en_button() {
        document.getElementById('form_read_only').disabled = true;
        document.getElementById('edit_en_button').style.display = 'block'
        document.getElementById('cancel_en_button').style.display = 'none'
        document.getElementById('save_en_button').style.display = 'none'
    }

    // function to submit edited email notification setting data
     $('#email_notif_form').submit(function () {
        event.preventDefault();
        console.log("form submitted!")
        var email_guid = document.getElementById("email_guid").value;
        console.log(email_guid)
        var email_subject = document.getElementById("email_subject").value;
        console.log(email_subject)
        var email_header = document.getElementById("email_header").value;
        var email_body = document.getElementById("email_body").value;
        var email_footer = document.getElementById("email_footer").value;
        $.ajax({
            type: 'POST',
            url: "{% url 'eProc_Emails:update_email_notif_form' %}",
            data: {
                'email_guid': email_guid,
                'email_subject': email_subject,
                'email_header': email_header,
                'email_body': email_body,
                'email_footer': email_footer,
            },
            success: function(response) {
                s_message = document.getElementById('success_message')
                s_message.innerHTML = response.message
                div_id = s_message.id
                timeout(div_id)
                cancel_en_button();
            }
        });
        return false;
    });

    function timeout(hideDiv) {
        setTimeout(function () {
            document.getElementById(hideDiv).innerHTML = '';
        }, 4000);
    }


//---------------------------------------------

function split(val) {
    return val.split('@');
}

function extractLast(term) {
    return split(term).pop();
}

function typeahead(id){
document.getElementById(id).addEventListener('keypress', (event) => {
      if ( event.keyCode == 64 ) {
        $('#'+id)
        // don't navigate away from the field on tab when selecting an item
        .bind("keydown", function(event) {
            if (event.keyCode === $.ui.keyCode.TAB && $(this).data("autocomplete").menu.active) {
                event.preventDefault();
            }
        }).autocomplete({
            minLength: 0,
            source: function(request, response) {
                var term = request.term,
                    results = [];
                if (term.indexOf("@") >= 0) {
                    term = extractLast(request.term);
                        results = $.ui.autocomplete.filter(
                         availableKeywords, term);
                }
                response(results);
            },
            focus: function() {
                // prevent value inserted on focus
                return false;
            },
            select: function(event, ui) {
                var terms = [];
                terms = split(this.value);
                var inputString = this.value;
                if (inputString.charAt(inputString.length - 1) == '@') {
                    var shortenedString = inputString.substr(0,(inputString.length -1));
                terms = [shortenedString]
                }
                // add the selected item
                terms.push(ui.item.value);
                this.value = terms.join("");
                return false;
            }
    });
        }
    });
}
</script>

{% endblock %}

eProc_Emails/templates/po_supplier_email.html
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}

<head>

</head>

<body>
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="650"
    style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;background-color:#E9ECEF;">
    <tbody>
      <tr class="context-header">
        <td style="color: white; background-color: #4E4E4E;" align="center">
          <div style="padding: 35px;">
            <img src="http://majjaka-eprocure.com/static/images/majjakalogo-white.png" style="width: 300px;">
          </div>
        </td>
      </tr>
      <tr class="context-body">
        <td style="padding: 20px;">
          <p>{{context.header|safe|linebreaksbr}}</p>
          <p>{{context.body|safe|linebreaksbr}}</p>
          <p>{{context.footer|safe|linebreaksbr}}</p>

        </td>
      </tr>
      <tr class="context-footer">
        <td style="color: rgb(212, 202, 202); background-color: #4E4E4E; font-size: 11px;" align="center">
          <p style="font-weight: 300; margin-top: 5px;">Unsubscribe | Help</p>
          <div style="padding: 5px;">
            <img src="http://majjaka-eprocure.com/static/images/majjakalogo-white.png" alt="" style="width: 100px;">
          </div>
          <p><a style="color: rgb(212, 202, 202);" href="https://majjaka.com/" target="_blank">www.majjaka.com</a></p>
          <p>© 2022 MajjakaProcure, Bangalore, Karnataka</p>
        </td>
      </tr>
    </tbody>
  </table>
</body>

</html>

eProc_Emails/templates/sc_completion_html_email.html
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}

<head>

</head>

<body>
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="650"
    style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;background-color:#E9ECEF;">
    <tbody>
      <tr class="context-header">
        <td style="color: white; background-color: #4E4E4E;" align="center">
          <div style="padding: 35px;">
            <img src="http://majjaka-eprocure.com/static/images/majjakalogo-white.png" style="width: 300px;">
          </div>
        </td>
      </tr>
      <tr class="context-body">
        <td style="padding: 20px;">
          <p>{{context.header|safe|linebreaksbr}}</p>
          <p>{{context.body|safe|linebreaksbr}}</p>
          <p>{{context.footer|safe|linebreaksbr}}</p>
          
        </td>
      </tr>
      <tr class="context-footer">
        <td style="color: rgb(212, 202, 202); background-color: #4E4E4E; font-size: 11px;" align="center">
          <p style="font-weight: 300; margin-top: 5px;">Unsubscribe | Help</p>
          <div style="padding: 5px;">
            <img src="http://majjaka-eprocure.com/static/images/majjakalogo-white.png" alt="" style="width: 100px;">
          </div>
          <p><a style="color: rgb(212, 202, 202);" href="https://majjaka.com/" target="_blank">www.majjaka.com</a></p> 
          <p>© 2022 MajjakaProcure, Bangalore, Karnataka</p>          
        </td>
      </tr>
    </tbody>
  </table>
</body>

</html>

eProc_Emails/templates/user_registration_email.html
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load static %}

<head>

</head>

<body>
  <table align="center" border="0" cellpadding="0" cellspacing="0" width="650"
    style="border: none; border-collapse: collapse; font-family:  Arial, sans-serif; font-size: 14px; line-height: 1.5;background-color:#E9ECEF;">
    <tbody>
      <tr class="context-header">
        <td style="color: white; background-color: #4E4E4E;" align="center">
          <div style="padding: 35px;">
            <img src="http://majjaka-eprocure.com/static/images/majjakalogo-white.png" style="width: 300px;">
          </div>
        </td>
      </tr>
      <tr class="context-body">
        <td style="padding: 20px;">
          <p>{{context.header|safe|linebreaksbr}}</p>
          <p>{{context.body|safe|linebreaksbr}}</p>
          <p>{{context.footer|safe|linebreaksbr}}</p>

        </td>
      </tr>
      <tr class="context-footer">
        <td style="color: rgb(212, 202, 202); background-color: #4E4E4E; font-size: 11px;" align="center">
          <p style="font-weight: 300; margin-top: 5px;">Unsubscribe | Help</p>
          <div style="padding: 5px;">
            <img src="http://majjaka-eprocure.com/static/images/majjakalogo-white.png" alt="" style="width: 100px;">
          </div>
          <p><a style="color: rgb(212, 202, 202);" href="https://majjaka.com/" target="_blank">www.majjaka.com</a></p> 
          <p>© 2022 MajjakaProcure, Bangalore, Karnataka</p>          
        </td>
      </tr>
    </tbody>
  </table>
</body>

</html>